# Generated by Django 4.0.2 on 2022-07-06 20:48

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('house', models.PositiveIntegerField()),
                ('markx', models.FloatField(default=-1)),
                ('marky', models.FloatField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('appreciations', models.IntegerField(default=0)),
                ('appreciatedUsers', models.TextField(blank=True)),
                ('unappreciatedUsers', models.TextField(blank=True)),
                ('date', models.DateField(default=datetime.datetime(2022, 7, 6, 20, 48, 24, 581338, tzinfo=utc))),
                ('reacted', models.JSONField(blank=True, default={})),
            ],
            options={
                'ordering': ['-appreciations', '-date'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickName', models.CharField(max_length=255)),
                ('profile_img', models.ImageField(upload_to='profiles')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=17, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('sessionExpTime', models.BigIntegerField(default=0)),
                ('prv_key', models.BigIntegerField(default=0)),
                ('refresh', models.TextField(default='0')),
                ('addresses', models.ManyToManyField(blank=True, to='Rule.Address')),
            ],
        ),
        migrations.CreateModel(
            name='RuleCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('addresses', models.ManyToManyField(blank=True, to='Rule.Address')),
            ],
        ),
        migrations.CreateModel(
            name='PostWithMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('imgs', models.TextField(blank=True, default='')),
                ('date', models.DateField(default=datetime.datetime(2022, 7, 6, 20, 48, 24, 580339, tzinfo=utc))),
                ('markx', models.FloatField(default=-1)),
                ('marky', models.FloatField(default=-1)),
                ('title', models.CharField(default='', max_length=255)),
                ('appreciations', models.IntegerField(default=0)),
                ('appreciatedUsers', models.TextField(blank=True)),
                ('unappreciatedUsers', models.TextField(blank=True)),
                ('reacted', models.JSONField(blank=True, default={})),
                ('comments', models.ManyToManyField(blank=True, to='Rule.Comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rule.user')),
            ],
            options={
                'ordering': ['-appreciations', '-date'],
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rule.user'),
        ),
        migrations.AddField(
            model_name='address',
            name='posts',
            field=models.ManyToManyField(blank=True, to='Rule.PostWithMark'),
        ),
    ]
