# Generated by Django 4.0.2 on 2022-04-15 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('house', models.PositiveIntegerField()),
                ('marks', models.JSONField(blank=True, default={})),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('reactions', models.JSONField()),
                ('appreciations', models.IntegerField()),
                ('appreciatedUsers', models.TextField(blank=True)),
                ('date', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickName', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=17, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('addresses', models.ManyToManyField(blank=True, to='Rule.Address')),
            ],
        ),
        migrations.CreateModel(
            name='RuleCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('addresses', models.ManyToManyField(blank=True, to='Rule.Address')),
            ],
        ),
        migrations.CreateModel(
            name='PostWithMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('imgs', models.TextField()),
                ('date', models.CharField(max_length=50)),
                ('reactions', models.JSONField()),
                ('markx', models.FloatField()),
                ('marky', models.FloatField()),
                ('appreciations', models.IntegerField()),
                ('appreciatedUsers', models.TextField(blank=True)),
                ('comments', models.ManyToManyField(blank=True, to='Rule.Comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rule.user')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rule.user'),
        ),
        migrations.AddField(
            model_name='address',
            name='posts',
            field=models.ManyToManyField(blank=True, to='Rule.PostWithMark'),
        ),
        migrations.AddField(
            model_name='address',
            name='users',
            field=models.ManyToManyField(blank=True, to='Rule.User'),
        ),
    ]
