# Generated by Django 4.0.1 on 2022-11-08 07:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Rule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 8, 7, 9, 17, 785152, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='postwithmark',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 8, 7, 9, 17, 785152, tzinfo=utc)),
        ),
    ]
