# Generated by Django 4.0.2 on 2022-09-16 11:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Rule', '0002_alter_comment_options_alter_postwithmark_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='district',
            new_name='street',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='reacted',
            new_name='reactions',
        ),
        migrations.RenameField(
            model_name='postwithmark',
            old_name='imgs',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='postwithmark',
            old_name='reacted',
            new_name='reactions',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='nickName',
            new_name='nick',
        ),
        migrations.RemoveField(
            model_name='address',
            name='markx',
        ),
        migrations.RemoveField(
            model_name='address',
            name='marky',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='appreciatedUsers',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='appreciations',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='unappreciatedUsers',
        ),
        migrations.RemoveField(
            model_name='postwithmark',
            name='appreciatedUsers',
        ),
        migrations.RemoveField(
            model_name='postwithmark',
            name='appreciations',
        ),
        migrations.RemoveField(
            model_name='postwithmark',
            name='markx',
        ),
        migrations.RemoveField(
            model_name='postwithmark',
            name='marky',
        ),
        migrations.RemoveField(
            model_name='postwithmark',
            name='text',
        ),
        migrations.RemoveField(
            model_name='postwithmark',
            name='unappreciatedUsers',
        ),
        migrations.AddField(
            model_name='address',
            name='users',
            field=models.ManyToManyField(blank=True, to='Rule.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comments',
            field=models.ManyToManyField(blank=True, to='Rule.Comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='rate',
            field=models.JSONField(default={'m': [], 'p': []}),
        ),
        migrations.AddField(
            model_name='postwithmark',
            name='images',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='postwithmark',
            name='mark',
            field=models.JSONField(default={'x': -1, 'y': -1}),
        ),
        migrations.AddField(
            model_name='postwithmark',
            name='rate',
            field=models.JSONField(default={'m': [], 'p': []}),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 9, 16, 11, 24, 55, 76362, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='postwithmark',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 9, 16, 11, 24, 55, 75362, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='RuleCompany',
        ),
    ]
