# Generated by Django 4.0.2 on 2022-04-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rule', '0002_comment_unappreciatedusers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='users',
        ),
        migrations.AlterField(
            model_name='address',
            name='marks',
            field=models.JSONField(blank=True, default={'marks': []}),
        ),
    ]
