# Generated by Django 4.0.2 on 2022-11-15 16:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Rule', '0002_alter_comment_date_alter_postwithmark_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 15, 16, 28, 38, 267506, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='postwithmark',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 15, 16, 28, 38, 265504, tzinfo=utc)),
        ),
    ]
