# Generated by Django 4.0.2 on 2022-04-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rule', '0003_remove_address_users_alter_address_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postwithmark',
            name='appreciations',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='postwithmark',
            name='reactions',
            field=models.JSONField(blank=True),
        ),
    ]
