# Generated by Django 4.0.1 on 2022-04-16 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rule', '0004_alter_postwithmark_appreciations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postwithmark',
            name='reactions',
            field=models.JSONField(default={}),
        ),
    ]
