# Generated by Django 4.0.2 on 2022-09-16 13:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Rule', '0004_alter_comment_date_alter_postwithmark_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sessionExpTime',
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 9, 16, 13, 22, 39, 69446, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='postwithmark',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 9, 16, 13, 22, 39, 68446, tzinfo=utc)),
        ),
    ]
