# Generated by Django 4.0.2 on 2022-09-18 10:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Rule', '0005_remove_user_sessionexptime_alter_comment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 9, 18, 10, 6, 59, 409571, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='postwithmark',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 9, 18, 10, 6, 59, 408571, tzinfo=utc)),
        ),
    ]
