# Generated by Django 4.0.1 on 2022-04-16 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rule', '0006_alter_comment_appreciations_alter_comment_reactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reactions',
            field=models.JSONField(default={'reactions': []}),
        ),
        migrations.AlterField(
            model_name='postwithmark',
            name='reactions',
            field=models.JSONField(default={'reactions': []}),
        ),
    ]
