# Generated by Django 4.0.1 on 2022-04-16 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rule', '0007_alter_comment_reactions_alter_postwithmark_reactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reactions',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='postwithmark',
            name='reactions',
            field=models.JSONField(default={}),
        ),
    ]
