# Generated by Django 4.0.2 on 2022-09-19 14:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Rule', '0007_alter_comment_date_alter_postwithmark_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='comments',
            field=models.ManyToManyField(blank=True, to='Rule.Comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 9, 19, 14, 56, 50, 128917, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='postwithmark',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 9, 19, 14, 56, 50, 127916, tzinfo=utc)),
        ),
    ]
