# Generated by Django 4.0.1 on 2022-04-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rule', '0008_alter_comment_reactions_alter_postwithmark_reactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reacted',
            field=models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='postwithmark',
            name='reacted',
            field=models.JSONField(default={}),
        ),
    ]
