# Generated by Django 4.0.1 on 2022-04-16 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rule', '0009_comment_reacted_postwithmark_reacted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reactions',
        ),
        migrations.RemoveField(
            model_name='postwithmark',
            name='reactions',
        ),
    ]
