# Generated by Django 4.0.2 on 2022-04-29 16:22

import Rule.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rule', '0012_user_prv_key_user_sessionexptime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=Rule.models.post_directory_path)),
            ],
        ),
        migrations.RemoveField(
            model_name='postwithmark',
            name='imgs',
        ),
        migrations.AddField(
            model_name='postwithmark',
            name='imgs',
            field=models.ManyToManyField(blank=True, to='Rule.Image'),
        ),
    ]
