# Generated by Django 4.0.2 on 2022-05-07 18:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Rule', '0013_image_remove_postwithmark_imgs_postwithmark_imgs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-appreciations', '-date']},
        ),
        migrations.AlterModelOptions(
            name='postwithmark',
            options={'ordering': ['-appreciations', '-date']},
        ),
        migrations.RemoveField(
            model_name='address',
            name='marks',
        ),
        migrations.RemoveField(
            model_name='user',
            name='surname',
        ),
        migrations.AddField(
            model_name='user',
            name='refresh',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 7, 18, 23, 20, 785695, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='postwithmark',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 7, 18, 23, 20, 783697, tzinfo=utc)),
        ),
    ]
