# Generated by Django 4.0.2 on 2022-05-07 19:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Rule', '0014_alter_comment_options_alter_postwithmark_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 7, 19, 53, 23, 378490, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='postwithmark',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 7, 19, 53, 23, 376490, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='refresh',
            field=models.TextField(default='0'),
        ),
    ]
