# Generated by Django 4.0.1 on 2022-05-09 06:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Rule', '0015_alter_comment_date_alter_postwithmark_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 9, 6, 24, 3, 449968, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='postwithmark',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 9, 6, 24, 3, 434355, tzinfo=utc)),
        ),
    ]
