# Generated by Django 4.0.1 on 2022-07-02 20:29

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Rule', '0018_alter_comment_date_alter_postwithmark_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 7, 2, 20, 29, 57, 359318, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='postwithmark',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 7, 2, 20, 29, 57, 358310, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Rule.image'),
        ),
    ]
