# Generated by Django 4.0.1 on 2022-07-02 20:33

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Rule', '0019_alter_comment_date_alter_postwithmark_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 7, 2, 20, 33, 56, 954203, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='postwithmark',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 7, 2, 20, 33, 56, 953186, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Rule.image'),
        ),
    ]
