# Generated by Django 4.0.1 on 2022-07-04 14:30

import Rule.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Rule', '0025_alter_comment_date_alter_postwithmark_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 7, 4, 14, 30, 31, 261868, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='postwithmark',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 7, 4, 14, 30, 31, 261868, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(upload_to=Rule.models.post_directory_path),
        ),
    ]
